name: Build Storm32 Arduino Project


on:
  push:
    branches:
      - main

      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
          
      - name: Install PlatformIO
        run: |
          pip install -U platformio
      - name: Build Storm32 Project
      
        run: |
          pio run -d storm32_v1_31_rc -b storm32_v1_31_rc.json --board storm32_v1_31_rc --ide arduino
          
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME: ${{ github.run_id }}
        with:
          tag_name: ${{ github.run_id }}
          body: ${{ steps.create_changelog.outputs.body }}
          draft: false
          prerelease: false
          
      - name: Create Changelog
        run: |
          git fetch --tags
          echo "## Changelog" >> $GITHUB_OUTPUT
          for tag in `git ls-remote --tags | egrep -o 'refs/tags/\d+\.\d+\.\d+(-beta\.\d+)?$' | sed 's-\(refs/tags/v\)||-'`
          do
            echo "- `git show -s --format=format:"%cD %an %s" ${tag}`" >> $GITHUB_OUTPUT
          done
