name: Build Arduino IDE project for Storm32

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: platformio/builder:arm-none-eabi-gcc@sha256:669ef078d50b4382e5233c390e2c17148025793404fd99f92cc496bc31235bca
    env:
      PIO_SECRETS: ${{ secrets.PIO_SECRETS }}
    steps:
      - uses: actions/checkout@v3

      - name: Create Project Folder structure
        run: |
          mkdir -p src
          mkdir -p lib

      - name: Copy Arduino IDE project files
        run: cp ../storm32.ino ./src/

      - name: Install platformio dependencies
        run: pio ci --dependencies

      - name: Build Project
        run: |
          cd src
          pio run -e storm32
          make upload_storm32

      - name: Upload output binary
        uses: actions/upload-artifact@v3
        with:
          name: binary
          path: build/storm32.elf
          retention-days: 1
