name: Generate Storm32 INO File

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  generate_ino:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Board JSON
        run: |
          curl https://raw.githubusercontent.com/kemp-zz/platform-ststm32/main/boards/storm32_v1_31_rc.json > board.json

      - name: Get PlatformIO INI
        run: |
          curl https://raw.githubusercontent.com/kemp-zz/platform-ststm32/main/tests/storm32/platformio.ini > platformio.ini

      - name: Generate Storm32 INO
        run: |
          echo "// This file is generated automatically" >> storm32.ino
          echo "#include <Arduino.h>" >> storm32.ino
          echo "" >> storm32.ino

          # Add board-specific defines
          jq '.defines // [] | .[] | .key + "=" + .value' board.json >> storm32.ino || true

          # Add platformio.ini settings
          cat platformio.ini >> storm32.ino

          # Add setup and loop functions
          echo "void setup() {" >> storm32.ino
          echo "  Serial.begin(9600);" >> storm32.ino
          echo "}" >> storm32.ino
          echo "" >> storm32.ino
          echo "void loop() {" >> storm32.ino
          echo "  Serial.println(\"Hello, Storm32!\");" >> storm32.ino
          echo "  delay(1000);" >> storm32.ino
          echo "}" >> storm32.ino

      - name: Upload INO File
        uses: actions/upload-artifact@v3
        with:
          name: storm32_ino
          path: storm32.ino
