name: Examples

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        example:
          - "examples/arduino-blink"
          - "examples/arduino-external-libs"
          - "examples/arduino-internal-libs"
          - "examples/arduino-mbed-doom"
          - "examples/arduino-mbed-rpc"
          - "examples/arduino-mxchip-azureiot"
          - "examples/arduino-mxchip-filesystem"
          - "examples/arduino-mxchip-sensors"
          - "examples/arduino-mxchip-wifiscan"
          - "examples/cmsis-blink"
          - "examples/libopencm3-1bitsy"
          - "examples/libopencm3-blink"
          - "examples/libopencm3-usb-cdcacm"
          - "examples/mbed-rtos-blink-baremetal"
          - "examples/mbed-rtos-custom-target"
          - "examples/mbed-rtos-ethernet-tls"
          - "examples/mbed-rtos-events"
          - "examples/mbed-rtos-filesystem"
          - "examples/mbed-rtos-mesh-minimal"
          - "examples/mbed-rtos-serial"
          - "examples/mbed-rtos-usb-keyboard"
          - "examples/mbed-rtos-sockets"
          - "examples/spl-blink"
          - "examples/stm32cube-hal-blink"
          - "examples/stm32cube-hal-eeprom-emulation"
          - "examples/stm32cube-hal-extmem-boot"
          - "examples/stm32cube-hal-iap"
          - "examples/stm32cube-hal-lcd"
          - "examples/stm32cube-hal-usb-device-dfu"
          - "examples/stm32cube-hal-wifi-client"
          - "examples/stm32cube-ll-blink"
          - "examples/zephyr-blink"
          - "examples/zephyr-cpp-synchronization"
          - "examples/zephyr-drivers-can"
          - "examples/zephyr-net-https-client"
          - "examples/zephyr-subsys-usb-hid-mouse"
          - "tests/arduino-blink-different-cores"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio pkg install --global --platform symlink://.
      - name: Build examples
        run: |
          pio run -d ${{ matrix.example }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME: ${{ github.run_id }}
        with:
          tag_name: ${{ github.run_id }}
          body: ${{ steps.create_changelog.outputs.body }}
          draft: false
          prerelease: false
      - name: Create Changelog
        run: |
          git fetch --tags
          echo "## Changelog" >> $GITHUB_OUTPUT
          for tag in `git ls-remote --tags | egrep -o 'refs/tags/\d+\.\d+\.\d+(-beta\.\d+)?$' | sed 's-\(refs/tags/v\)||-'`
          do
            echo "- `git show -s --format=format:"%cD %an %s" ${tag}`" >> $GITHUB_OUTPUT
          done
